### PR TITLE
WIP: Added 80% minimum coverage threshold

### PR DESCRIPTION
**Pull request by photodow**
### Description

This pull request adds a minimum 80% code coverage threshold to all of our packages. This appeared to have been decided via side conversations and slack channels.

> *This pull request may continue to fail tests until we get the proper testing in place.*
> See #121 as an example

### Changelog

**New**

- 80% minimum code coverage

### CODE REVIEW

**Comment by photodow** [comment]
@jeffchew it might. 😂

I think we're definitely under the `80%` threshold in a couple of areas, but hopefully, it won't take much to bump it up. I think footer #121 should help too. It looks like it won't block a PR until @annawen1 gets that fix in though.

**Comment by kennylam** [comment]
@jeffchew @photodow @annawen1 I'll test CI locally and let you guys know

**Comment by kennylam** [comment]
@photodow @jeffchew @annawen1 
No go amigos :frowning:

But pretty close

Screen Shot 2019-09-24 at 3 16 54 PM

**Comment by photodow** [comment]
@kennylam then let's get #121 reviewed and merged and try again. 😉

**Comment by kennylam** [comment]
@photodow There are a few test errors in your footer unit tests. Run a `yarn jest` in `/packages/react` and you'll see.

**Pull request closed without merging**
