### PR TITLE
style(ToC): increasing mobile component clickable area

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

[TOC] tablet, mobile interaction #3726

### Description

**What's happening**

The mobile version of the `ToC` have a small clickable area, as the following image shows: 
Captura de Tela 2020-09-03 às 10 08 19

**What should happen**

The mobile version of the `ToC` should have a bigger clickable area, as shown below: 
Captura de Tela 2020-09-03 às 10 10 43

### Changelog

**New**

- CSS rule at `TableOfContents` SASS file.

### CODE REVIEW

**Review by jeffchew — DISMISSED** [review]
LGTM!

**Comment by annawen1** [comment]
hmm not sure if the bug is valid? I tried clicking the toc bar outside of the "clickable" area in the 1st screenshot - like all the way to the right of the text - in our current canary version and it works fine. I tested this on https://www.ibm.com/testing/solutions on my phone too. Should I be testing somewhere else?

**Comment by guilhermelMoraes** [comment]
@annawen1 I've tested on my local environment, on the [canary](http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-table-of-contents--manually-define-menu-items) and in my phone. In all these places I was able to reproduce the bug. 
This isn't hard to fix on the fly. I've made this fix locally on the new Support page, as well. 

FYI @jeffchew

**Comment by guilhermelMoraes** [comment]
@annawen1 @jeffchew any updates on that one?

**Comment by annawen1** [comment]
> @annawen1 I've tested on my local environment, on the [canary](http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-table-of-contents--manually-define-menu-items) and on my phone. In all these places I was able to reproduce the bug.
> This isn't hard to fix on the fly. I've made this fix locally on the new Support page, as well.
> 
> FYI @jeffchew

Interesting, I was testing in the DotcomShell and the issue doesn't exist there, but in the TOC story itself I see the bug. I'll approve the fix!

**Review by annawen1 — APPROVED** [review]

**Pull request merged**
