### PR TITLE
Masthead/iconfix

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

https://github.com/carbon-design-system/ibm-dotcom-library/issues/1098

### Description

Fixes the misalignment of the profile icon on the masthead

Before the fix:
Screen Shot 2020-01-30 at 3 02 02 PM

After: 
Screen Shot 2020-01-30 at 3 02 17 PM

### CODE REVIEW

**Comment by andysherman2121** [comment]
Gotcha i'll take a look Kenny

**Comment by jeffchew** [comment]
@andysherman2121 this PR is getting a bit stale, was there something that needed to be wrapped up here?

cc: @annawen1 @kennylam

**Comment by andysherman2121** [comment]
> @andysherman2121 this PR is getting a bit stale, was there something that needed to be wrapped up here?
> 
> cc: @annawen1 @kennylam

Yeah the icon is still pulling in some of the carbon styling, I'll be working on getting this fixed and merged in the next day

**Comment by kennylam** [comment]
> Also looks off in the expressive version
> 
> Screen Shot 2020-02-03 at 8 44 21 AM

@andysherman2121 this still looks unresolved?

**Pull request merged**
