### PR TITLE
fix(LightboxMediaViewer): have image appear on mobile landscape

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

Component:Image with Caption:- Caption text is overlapping on image in landscape mode.(Mobile) #2445
Component: Image With Caption :- On mobile device in landscape mode image is not visible. #2768

### Description

Bug: Image in lightbox wasn't appearing when mobile device is in landscape mode.

Screen Shot 2020-06-17 at 3 05 25 PM

### Changelog

**Changed**

- set `.#{$prefix}--lightbox-media-viewer__media, .#{$prefix}--lightbox-media-viewer__media .#{$prefix}--image` to 100% width and height

### CODE REVIEW

**Comment by jeffchew** [comment]
@annawen1 not sure if it's me, it doesn't appear in portrait now...

**Comment by kennylam** [comment]
> not sure if it's me, it doesn't appear in portrait now...

I'm seeing the same. It appears in landscape, but can't scroll.

**Comment by annawen1** [comment]
> > not sure if it's me, it doesn't appear in portrait now...
> 
> I'm seeing the same. It appears in landscape, but can't scroll.

hmmm yeah I'm seeing the same in an actual device...looking into it

**Comment by jeffchew** [comment]
Tabling for now, this seems to be tricker than it seems according to @annawen1 .

**Pull request closed without merging**
