### PR TITLE
chore(LeadspaceBlock): update story

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#3078 

### Description

Separate component variations into individual stories

### Changelog

**Changed**

- add stories for different variations (image, video)

### CODE REVIEW

**Comment by jeffchew** [comment]
@kennylam for videos, we might need to add a percy-only class to suppress videos to remove any false positives: https://github.com/carbon-design-system/ibm-dotcom-library/blob/2df0086c99e41db06b55fe9ed42f6e130b4c1973/packages/react/.storybook/preview-head.html#L145

**Comment by asudoh** [comment]
@jeffchew I see, do you have more details? Is it worth a new issue...? Thanks!

**Comment by jeffchew** [comment]
> @jeffchew I see, do you have more details? Is it worth a new issue...? Thanks!

Yes, this is creating regions that are essentially ignored in percy snapshot tests. For instance, waiting for a video player to load in which could cause some false positive snapshot tests. We are already doing that in some places in React. More documentation here:

https://docs.percy.io/docs/percy-specific-css#hiding-regions-with-percy-specific-css

We could create a separate issue for this for web components.

**Comment by asudoh** [comment]
Thanks @jeffchew! Created: #3242

**Comment by kennylam** [comment]
> @kennylam for videos, we might need to add a percy-only class to suppress videos to remove any false positives

@jeffchew I see, done!

**Pull request merged**
