### PR TITLE
docs(examples): introduce CodeSandbox for Web Components

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #3059.

### Description

Introduces CodeSandbox examples for Web Components.
Also fixes following issues found in CodeSandbox examples:

* `<dds-link-with-icon>` broken in CodeSandbox
* `<dds-modal-close-button>` has wrong size

### Changelog

**New**

- CodeSandbox examples for Web Components

**Changed**

- Fixes to `<dds-link-with-icon>` and `<dds-modal-close-button>` for CodeSandbox

### CODE REVIEW

**Comment by jeffchew** [comment]
Thank you @asudoh ! One thing, can we have links out to the corresponding codesandbox in the READMEs for each component?

**Comment by asudoh** [comment]
@jeffchew Sure, updated.

**Comment by jeffchew** [comment]
> @jeffchew Sure, updated.

Thanks @asudoh , what I meant was create a link that goes out to codesandbox and not iframing it (what you had before was fine):

https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/src/components/VideoPlayer/README.stories.mdx#video-player

Apologies if I wasn't clear!

**Comment by asudoh** [comment]
I see thank you for clarifying @jeffchew - Updated.

**Pull request merged**
