### PR TITLE
fix(scss): reinforced link-list pattern styling selectors

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

#1733 

### Description

I've updated the selectors for `LinkList` and `TableOfComponents` so they are more specific to the patterns.

### Changelog

**Changed**

- SCSS Selectors

### CODE REVIEW

**Comment by annawen1** [comment]
Im actually kind of confused by how the styles are being overwritten...

Isn't `.bx--link-list .bx--card__copy p` and `.bx--tableofcontents .bx--tableofcontents__content p` specific to the `linked list` and `table of contents` respectively? How is it that those styles are affecting link list?

**Comment by jeffchew** [comment]
> Im actually kind of confused by how the styles are being overwritten...
> 
> Isn't `.bx--link-list .bx--card__copy p` and `.bx--tableofcontents .bx--tableofcontents__content p` specific to the `linked list` and `table of contents` respectively? How is it that TOC styles are affecting link list?
> 
> @jeffchew @kennylam

I think it's because in this scenario, the `LinkList` is nested under the `TableOfContents` so those `p` styles were messing with the `LinkList` `p` styles...

cc: @RaphaelAmadeu

**Comment by RaphaelAmadeu** [comment]
> > Im actually kind of confused by how the styles are being overwritten...
> > Isn't `.bx--link-list .bx--card__copy p` and `.bx--tableofcontents .bx--tableofcontents__content p` specific to the `linked list` and `table of contents` respectively? How is it that TOC styles are affecting link list?
> > @jeffchew @kennylam
> 
> I think it's because in this scenario, the `LinkList` is nested under the `TableOfContents` so those `p` styles were messing with the `LinkList` `p` styles...
> 
> cc: @RaphaelAmadeu

Exactly, `TableOfContents` were overwriting the intended color

**Comment by jeffchew** [comment]
Going to merge this, looks like CircleCI completed successfully but never reported back:
https://app.circleci.com/pipelines/github/RaphaelAmadeu/ibm-dotcom-library/412/workflows/2834a627-4fc7-4b38-8ac8-1c708aa065cf/jobs/566

**Pull request merged**
