### PR TITLE
feat(videoplayer): add closed captions

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#4012 

### Description

Add closed caption button to `VideoPlayer`.

### Changelog

**New**

- closed captioning button to Kaltura video player

### CODE REVIEW

**Comment by IgnacioBecerra** [comment]
I'm assuming actual close captions would replace "Test Video - 1:1 (0:18)" under the video, correct?

**Comment by kennylam** [comment]
> I'm assuming actual close captions would replace "Test Video - 1:1 (0:18)" under the video, correct?

It will add the CC button if the video has captions.

image

Currently only working locally, as the Kaltura environment variables for deploy previews needs to be changed to view the videos (examples in any of the `CTA` video variations).

image

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @kennylam!

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
