### PR TITLE
fix(theme): removed inverse theme for Imagewithcaption, videoplayer and contentblocksimple

### PR DESCRIPTION
**Pull request by greeshmareddyg**
### Related Ticket(s)

https://github.com/carbon-design-system/ibm-dotcom-library/issues/3192

### Description

Removed Inverse theme for Imagewith caption, videoplayer and contentblocksimple components.

### Changelog

**Removed**
Inverse theme for below components
Imagewith caption, 
videoplayer and 
contentblocksimple components.

### CODE REVIEW

**Comment by asudoh** [comment]
BTW would you update the snapshot? Thanks!

**Comment by greeshmareddyg** [comment]
> BTW would you update the snapshot? Thanks!

@asudoh yeah, I will update it.

**Comment by jeffchew** [comment]
@greeshmareddyg tests still appear to be failing, the snapshots look out of sync still.

**Comment by greeshmareddyg** [comment]
> Theme looks off for CalloutWithMedia:
> 
> Screen Shot 2020-07-22 at 5 45 09 PM

@jeffchew For the calloutwithmedia we are using contentblocksimple inverse, as we are removing inverse for that component shall I apply g90 theme styles to calloutwithmedia, or shall I enable theme styles to contentblocksimple. could you suggest.

**Comment by kennylam** [comment]
Moved to #3301

**Pull request closed without merging**
