### PR TITLE
feat(MastheadL1): graduate masthead L1 from experimental

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4010.

### Description

This change graduates masthead L1 from experimental, making it available without `DDS_MASTHEAD_L1` feature flag.

`DDS_MASTHEAD_L1` feature flag has been removed.

Also removed the following:

* Eyebrow feature from Masthead L1, given the new design does not seem to have the space for eyebrow and the the story that demonstrates the eyebrow does not seem to be working.
* Short variant of Masthead L1, given it doesn't seem to be demonstrated in storybook.

### Changelog

**New**

- Masthead L1 feature available without a feature flag

**Changed**

- The styles of masthead L1

**Removed**

- `DDS_MASTHEAD_L1` feature flag
- Eyebrow feature from Masthead L1that demonstrates the eyebrow does not seem to be working.
- Short variant of Masthead L1

### CODE REVIEW

**Comment by asudoh** [comment]
Any missing L1 features? Any design implementation that is missing? CC @guilhermelMoraes @kennylam @annawen1 Thanks!

**Comment by annawen1** [comment]
> Should L1 nav data be from our services? Any missing L1 features? Any design implementation that is missing? CC @guilhermelMoraes @kennylam @annawen1 Thanks!

Ah! L1 needs to support the MegaMenu too which I haven't implemented yet. I can create a PR to merge into this one.

**Comment by asudoh** [comment]
Oh that will be splendid - I think you can add a commit to my branch here, but please let me know otherwise. Thanks you so much @annawen1!

**Comment by jeffchew** [comment]
@asudoh looks good! Can L1 be a separate story instead of a checkbox? Would be good to have percy coverage for this.

**Comment by asudoh** [comment]
@jeffchew Makes sense - Done.

**Review by jeffchew — APPROVED** [review]
@asudoh looks good to me!

One final thing though, can you delete the feature flag from `FeatureFlags.js`?

**Comment by asudoh** [comment]
@jeffchew Updated the snapshot. I thought I had removed the feature flag, but please let me know if I'm missing anything. Thanks!

**Review by jeffchew — APPROVED** [review]
Sorry I must have missed it when scrolling through the changes. Thank you!

**Comment by asudoh** [comment]
Merging, once it happens @annawen1 you can base your change on `master`. Thanks!

**Pull request merged**
