### PR TITLE
chore(callout): drift away from BEM concatenation

### PR DESCRIPTION
**Pull request by asudoh**
### Description

This change to callout style drifts away from BEM concatenation, so the style can be reused with Web Components.

### Changelog

**Changed**

- A change to callout style drifts away from BEM concatenation, so the style can be reused with Web Components.

### CODE REVIEW

**Comment by jeffchew** [comment]
@asudoh a PR was just opened by @RaphaelAmadeu (https://github.com/carbon-design-system/ibm-dotcom-library/pull/3983), is this one still needed?

**Comment by RaphaelAmadeu** [comment]
> @asudoh a PR was just opened by @RaphaelAmadeu (#3983), is this one still needed?

@jeffchew This one edits the media and data variants of `callout`, the another pr only handled the default version, so this is still needed.

**Review by jeffchew — APPROVED** [review]
Thank you for confirming @asudoh !

**Comment by asudoh** [comment]
Thanks @RaphaelAmadeu for actually confirming! 😉

**Pull request merged**
