### PR TITLE
chore(leadspace): drift away from BEM concatenation

### PR DESCRIPTION
**Pull request by asudoh**
### Description

This change to leadspace style drifts away from BEM concatenation, so the style can be reused with Web Components.

### Changelog

**Changed**

- A change to leadspace style drifts away from BEM concatenation, so the style can be reused with Web Components.

### CODE REVIEW

**Comment by jeffchew** [comment]
@asudoh Lead space content has been bumped up in this change, can you look?

Screen Shot 2020-09-16 at 1 37 14 PM

**Comment by asudoh** [comment]
Great catch @jeffchew - Fixed.

**Comment by jeffchew** [comment]
Thanks @asudoh ! It definitely looks better, but there's still a diff and looks a bit squished:

Screen Shot 2020-09-17 at 4 07 06 PM

**Comment by asudoh** [comment]
Another great catch @jeffchew thanks! Fixed.

**Review by jeffchew — APPROVED** [review]
Thank you @asudoh !

**Pull request merged**
