### PR TITLE
feat(table-of-contents): introduction

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #3632.

### Changelog

**New**

- `<dds-table-of-contents>`, the table of contents.

### CODE REVIEW

**Comment by jeffchew** [comment]
This looks great @asudoh ! I'm actually ready to merge this in as-is, but from a story perspective, I don't see some of the features that exist in React like heading content, optional rule, sticky offset, or ability to manually set the menu items. We should also have some kind of documentation on setting up the anchor links and what `data-title` does when doing the automatic version.

**Comment by asudoh** [comment]
@jeffchew Thank you for your feedback, fixed the missing horizontal rule, you can see it at the Other knob at With Heading Content story. You can see the demo of heading content (image) there as well.

With regard to the ability to manually set the menu items, I saw the code in React, but couldn't see any in the story demonstrating that feature. Wondering if I'm missing anything...

**Comment by jeffchew** [comment]
Hey @asudoh ,

The manually defined items is the `menuItems` prop in the React version:

Screen Shot 2020-10-01 at 10 01 37 AM

As for the docs, I don't see the prop table getting populated in the README.

**Comment by asudoh** [comment]
@jeffchew As we talked offline, update the doc of `<slot>`s and sticky offset thing. Thanks again for your feedback!

**Review by jeffchew — APPROVED** [review]
LGTM! Can you update snapshots?

**Pull request merged**
