### PR TITLE
Fix/link with icon

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

Related to ticket #540 
### Description

I've tried to align the text to the center of the element more properly by using flex, so it would be displayed properly on the focus state.

Screen Shot 2019-12-20 at 11 35 19

### CODE REVIEW

**Comment by photodow** [comment]
@oliviaflory we need your sharp eyes on this. Please! 😄

**Comment by jeffchew** [comment]
> @RaphaelAmadeu @wonilsuhibm @oliviaflory is it an issue that the link icon is now a block element? Meaning it won't sit inline to other text and inline elements?
> 
> image
> 
> vs...
> 
> image
> 
> > P.S. ignore the misalignment, I think that's different types paired up. Sorry, but hopefully you still get what I'm trying to say! 😅

Were we always allowing a link with icon to be inline? I guess that's more of a question for @wonilsuhibm @oliviaflory @larahanlon2

**Comment by oliviaflory** [comment]
@photodow @jeffchew @RaphaelAmadeu 

The first issue I see is that the link text is 14px/18px, and should be 16px/22px, that might help with the misaligned line heights?


Ideally we would not have a text+icon component inline, but as James has pointed out before, there's nothing stopping our adopters 😅 

We will hopefully be able to write guidelines to steer adopters away from this implementation *within a paragraph* like this
image

However, I can see this example where multiple links could be stacked on top of each other. 

image

The focus state extending so far past the end of the icon is not great. The focus state should end right after the icon, like this:
Screen Shot 2020-01-02 at 5 00 34 PM

**Comment by wonilsuhibm** [comment]
re preventing link with icon from being used inline, us there anything tbat can be done via `block` dispkay setting?

**Comment by annawen1** [comment]
> @photodow @jeffchew @RaphaelAmadeu
> 
> The first issue I see is that the link text is 14px/18px, and should be 16px/22px, that might help with the misaligned line heights?
> 
> Ideally we would not have a text+icon component inline, but as James has pointed out before, there's nothing stopping our adopters 😅
> 
> We will hopefully be able to write guidelines to steer adopters away from this implementation _within a paragraph_ like this
> image
> 
> However, I can see this example where multiple links could be stacked on top of each other.
> ...

So the font-size and line-height will adjust to 16px/22px once we turn the `REACT_STORYBOOK_CARBON_EXPRESSIVE` env var flag on

Screen Shot 2020-01-03 at 2 53 51 PM

**Pull request merged**
