### PR TITLE
fix(leadspace): buttons now display properly at 672px breakpoint

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#3297 

### Description

At 672px (md) breakpoint, adding more than 3 buttons would make the primary button would be counted as "overflow", and thus wouldn't display properly. By restructuring the children elements of`leadspace__content` to `position: relative`, the outer `section` would take into account the additional buttons included and wrap around them properly.

Before:

After:

### Changelog

**Changes**

- Refactored layout rules to accommodate for md breakpoint

### CODE REVIEW

**Review by kennylam — DISMISSED** [review]
@IgnacioBecerra It looks like removing the overflow is affecting the layout with image

image

**Comment by kennylam** [comment]
@IgnacioBecerra It looks like removing the overflow is affecting the layout with image

image

**Comment by IgnacioBecerra** [comment]
Fixed layout issue @kennylam mentioned but discovered another issue with the image variation, where the image doesn't cover the button layout at 672px.



Will revert the PR to a draft until I fix it.

**Review by kennylam — APPROVED** [review]
Looks good thanks @ignacio-becerra

**Pull request merged**
