### PR TITLE
feat(markdownToHTML): adds full markdown support

### LINKED ISSUE #2551: Change the Markdown utility based on the recent Reboot Learn template designs
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
change the `Markdown Utility`

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Once sized, the development work should be finished by the end of sprint 20-11 (June 5).  DDS has committed to Reboot that this pattern will be included in the June release.
- **See the Epic for the Design and Functional specs information**
- Design QA testing issue (#2552 )
- Prod QA testing issue (#2553 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Lila Title, when development is finished
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished
- [ ] The Canary URL is added to the Prod QA issue for their testing
- [ ] The Storybook link is added to the Design QA issue for their testing

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

Fixes #2551 

### Description

This adds full markdown support to content. While all markdown syntax is supported, not all css styles are included and will be added as needed, as well as any attributes required (`class`, `aria`, etc). These can be added to the custom renderer in the utility. 

Current syntaxes supported are:
- italics
- bold
- paragraphs
- ordered/unordered lists
- anchor links

Example link and list [here](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2715/index.html?path=/story/patterns-blocks-contentblockmedia--default).

### Changelog

**New**

- [Marked](https://github.com/markedjs/marked) package for full markdown support
- [DOMPurify](https://github.com/cure53/DOMPurify) package to sanitize output (`dangerouslySetInnerHTML`)
- css styling for ordered/unordered lists
- add prop blocks to `LocaleModalCountries`

**Changed**

- updated Storybook content

**Removed**

- custom regex for bold, italic, paragraphs

### CODE REVIEW

**Comment by kennylam** [comment]
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2715/index.html?path=/story/patterns-blocks-contentblockmedia--default

**Comment by jeffchew** [comment]
@kennylam do we have to worry about inverse here for the list items?

Screen Shot 2020-06-11 at 4 36 07 PM

**Comment by kennylam** [comment]
> @kennylam do we have to worry about inverse here for the list items?

@jeffchew looks like this got resolved in https://github.com/carbon-design-system/ibm-dotcom-library/pull/2735

**Comment by kennylam** [comment]
GH test integration build errors fixed in https://github.com/carbon-design-system/ibm-dotcom-library/pull/2740

**Pull request merged**
