### PR TITLE
chore(lightbox-video-player): remove redundant method

### PR DESCRIPTION
**Pull request by asudoh**
### Description

Removes a method from `<dds-lightbox-video-player>`, given no longer inherits `HybridRenderMixin` and such method is no longer used.

Also fixes a wrong class name.

### Changelog

**Changed**

- Fixes a wrong class name in `<dds-lightbox-video-player>`.

**Removed**

- A method from `<dds-lightbox-video-player>`

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM thanks @asudoh

**Comment by jeffchew** [comment]
@asudoh something odd happening here, can you take a look?

Screen Shot 2020-10-08 at 12 56 00 PM

**Comment by asudoh** [comment]
Good catch @jeffchew - Fixed.

**Comment by kennylam** [comment]
@asudoh Looks like you need to update the snapshots.

**Comment by asudoh** [comment]
Great catch thanks @kennylam - Updated.

**Pull request merged**
