### PR TITLE
chore(storybook): update to storybook 5.2.1

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

No related tickets

### Description

This upgrades storybook to v5.2.1.

### Changelog

**Changed**

- Storybook version 5.2.1

### CODE REVIEW

**Comment by jeffchew** [comment]
> Not sure if it's related to the storybook update but the react package netlify links look busted

Wow, didn't see that locally. Will have to take a look at this.

**Comment by kennylam** [comment]
> Wow, didn't see that locally. Will have to take a look at this.

@annawen1 @jeffchew This is happening on to others upgrading to the latest version
https://github.com/acl-services/paprika/pull/189#issuecomment-532063939

**Comment by jeffchew** [comment]
We'll close this PR for now until this gets resolved on their end.

**Comment by nahumzs** [comment]
We recently experienced the same issue, we recently solved it.  Maybe you are suffering from the same issue. 

You can read what was happening in our end.
https://github.com/storybookjs/storybook/issues/8138#issuecomment-546474491

**Comment by jeffchew** [comment]
> We experienced the same issue, we recently solved it.
> 
> You can read what was happening in our end, maybe can help with yours.
> [storybookjs/storybook#8138 (comment)](https://github.com/storybookjs/storybook/issues/8138#issuecomment-546474491)

@nahumzs thank you for circling back on this! We will take a look and probably reopen this task!

cc: @annawen1 @kennylam @photodow

**Pull request closed without merging**
