### PR TITLE
fix(mobile): first attempt to fix target-scrolling on ios 12

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

#1381 
### Description

I've changed the method used from `scrollIntoView` to `scrollTo`

### Changelog

**Changed**

- Mobile "Scroll to" handling

### CODE REVIEW

**Comment by photodow** [comment]
@RaphaelAmadeu one suggestion is @mkothur I believe got his smooth scroll utility merged in. Maybe we can switch it out, and work on improving the utility instead?

#1171

**Comment by RaphaelAmadeu** [comment]
> @RaphaelAmadeu one suggestion is @mkothur I believe got his smooth scroll utility merged in. Maybe we can switch it out, and work on improving the utility instead?
> 
> #1171


@photodow From what I could investigate until now, the problem of the scroll not happening on the iphone is due to the`scrollIntoView` not being supported by mobile safari, the fix I've tried was changing it to `scrollTo`

**Comment by photodow** [comment]
Right, so if we make that change in the utility then the fix can be applied across the board.

**Comment by RaphaelAmadeu** [comment]
First, let's ask for the QA team to test if this solution works with IOS 12, if it does, I can work along with @mkothur in order to implement this and solve this problem on future components that could use the scrolling.

**Pull request closed without merging**
