### PR TITLE
fix(localeModal): add outline

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#3406

### Description

add outline to cards
Screen Shot 2020-08-06 at 1 43 53 PM

### Changelog

**New**

- outline styles to link

### CODE REVIEW

**Comment by jeffchew** [comment]
@ariellalgilmore this looks good, though I'm wondering if we should actually take this opportunity to modify the styles in the styles package instead, so that we can reduce the separate styles code in `web-components`? 

cc: @asudoh @kennylam @annawen1 @RaphaelAmadeu @andysherman2121

**Comment by asudoh** [comment]
@jeffchew Good question, to do that, we need to make sure a CSS ruleset with `.#{$prefix}--locale-modal-container .#{$prefix}--locale-modal__regions .#{$prefix}--card` selector is applied to `:host(dds-region-item) .#{$prefix}--link`.

**Comment by jeffchew** [comment]
> @jeffchew Good question, to do that, we need to make sure a CSS ruleset with `.#{$prefix}--locale-modal-container .#{$prefix}--locale-modal__regions .#{$prefix}--card` selector is applied to `:host(dds-region-item) .#{$prefix}--link`.
> 
> Changes to `styles` packages in #3411 will be a good reference to see how we can make such change to locale modal.

@ariellalgilmore @asudoh I created issues like this to be lined up: https://github.com/carbon-design-system/ibm-dotcom-library/issues/3471

Should I make one for Locale Modal (actually I think I will...)? I think doing that will solve this bug.

**Comment by asudoh** [comment]
@jeffchew Yes makes sense.

**Comment by ariellalgilmore** [comment]
@jeffchew just confirming this can be closed and should be fixed here: #3482

**Pull request closed without merging**
