### PR TITLE
fix(CardLink): `bx--grid--condensed` added to the storybook story

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

CardLink: On a mobile device, the card is not stretched end-end of the mobile screen. #2609

### Description

This isn't a problem with the component, only with its story

### Changelog

**New**

- `bx--grid--condensed` class to the CardLink story;

### CODE REVIEW

**Comment by annawen1** [comment]
@guilhermelMoraes I'm looking at the deploy preview link and it still looks like it doesn't stretch the full width of the screen on mobile

Screen Shot 2020-06-16 at 10 11 29 AM

**Comment by guilhermelMoraes** [comment]
@annawen1 it's supposed to fulfill the entire screen when it's smaller than 320px, right? 
Captura de Tela 2020-06-16 às 11 15 26

**Comment by jeffchew** [comment]
@guilhermelMoraes can you update jest snapshots?

**Comment by guilhermelMoraes** [comment]
@jeffchew updated the snapshot and noticed that the LightBoxMediaViewer is throwing an error:

Captura de Tela 2020-06-16 às 11 39 06

Captura de Tela 2020-06-16 às 11 44 49

**Comment by jeffchew** [comment]
@guilhermelMoraes try doing a `yarn reset`, the utilities package has been updated so you might need to rebuild locally.

**Pull request merged**
