### PR TITLE
feat(masthead): support for dynamic language switch

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #3899.

### Description

Introduces code to load language display data as well as translation data with the new language when `language` property is changed in `<dds-masthead-container>`, `<dds-footer-container>` or `<dds-locale-modal-container>`.

To make it work, did the following changes:

* Add support specifying a specific language in `loadLangDisplay()`, `loadLocaleList()` and `loadTranslation()` Redux actions.
* Make Redux data for display language managed per language.
* Unsupport custom links data from `<dds-masthead-container>`, `<dds-footer-container>` and `<dds-locale-modal-container>`. For such use case, `-composite` counterparts should be used. Tests are changed to reflect such change.

Also, eliminated duplicate type definitions found during the effort.

dynamic-lang-switch

### Changelog

**New**

- Code to load language display data as well as translation data with the new language when `language` property is changed in `<dds-masthead-container>`, `<dds-footer-container>` or `<dds-locale-modal-container>`.
- Support specifying a specific language in `loadLangDisplay()`, `loadLocaleList()` and `loadTranslation()` Redux actions.

**Changed**

- A change to make Redux data for display language managed per language.

**Removed**

- Support for custom links data from `<dds-masthead-container>`, `<dds-footer-container>` and `<dds-locale-modal-container>`. For such use case, `-composite` counterparts should be used. Tests are changed to reflect such change.

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
Nice change, and thank you for getting this in right before code freeze!

**Comment by jeffchew** [comment]
@asudoh Just had a thought, this might affect the codesandbox examples since links is no longer supported, right?

**Comment by asudoh** [comment]
@jeffchew Here's what will happen as far as I know; In the environment where we explicitly set e.g. `.navLinks`, the API calls to get the corresponding data fails. And thus nothing will override the `.navLinks` we explicitly set and thus it still works.

**Comment by jeffchew** [comment]
> @jeffchew Here's what will happen as far as I know; In the environment where we explicitly set e.g. `.navLinks`, the API calls to get the corresponding data fails. And thus nothing will override the `.navLinks` we explicitly set and thus it still works.

Sounds good! Still seeing unrelated issues around codesandbox so will ping you offline on that.

**Pull request merged**
