### PR TITLE
fix(masthead): locked focus while left menu active

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

#3663 

### Description

I've added a focus sentinel so it prevent focus going out of the left menu while expanded.

### CODE REVIEW

**Comment by jeffchew** [comment]
@RaphaelAmadeu I see a small button in the mobile/tablet menu:

Screen Shot 2020-08-24 at 7 23 46 PM

**Comment by RaphaelAmadeu** [comment]
@jeffchew I've missed a file in my last commit, it should be ok now

**Comment by jeffchew** [comment]
@RaphaelAmadeu this looks good! One thing I noticed though is when going forward or back in the menu levels, it doesn't move focus to the newly selected menu list. If you tab, it goes into there though. But the original bug doesn't appear to be there as far as I can tell!

**Comment by asudoh** [comment]
Hi @jeffchew I think I had a discussion with @kennylam on this one. The consensus is that we apply a similar fix to #3348. I think from the discussion #3348 includes a change to `@carbon/ibmdotcom-utilities` package to extract out non-framework-specific part of #3348.

However as long as it's functional and doesn't cause any regression, I'm fine going with this change.

**Comment by jeffchew** [comment]
@asudoh let's move forward with this then and cut the release.

**Pull request merged**
