### PR TITLE
fix(Card): border covering 4 sides on actived or focused

### PR DESCRIPTION
**Pull request by diegomarcuz**
### Related Ticket(s)

Component: - CTA - Keyboard - Visual focus is not covering all 4 sides of the element #2722

### Description

When card as block cta is 'activated' or 'focused', in other words, has the pseudo element (:active or :focus), border needs to be on 4 sides of the card.

**Note**: Besides issue (#2722) is about CTA component, I need to fix on the Card component

image

### Changelog

**New**

1. added **active** and **focus** pseudo element for the `bx--card__CTA` class on the **index.scss** card component file.
2. when these two pseudo element happens, `z-index: -1` and `position: relative` is set so the stacking order of the image is lower than the CTA itself. 
- in terms of code, what happens is: 

~~~scss
&__CTA {
  &:focus,
  &:active {
   .#{$prefix}--image__img {
        position: relative;
        z-index: -1;
    }
  }
}
~~~

**Changed** 
- As @annawen1 (https://github.com/carbon-design-system/ibm-dotcom-library/pull/2922#issuecomment-650363404) sent a feedback about visibility of the image when the card is **active** or **focused**, I need to update the code with `position: relative` and `z-index: 2` for the `bx--card__CTA`, as shown below.

~~~scss
&__CTA {
  &:focus,
  &:active {
     position: relative;
     z-index: 2;

     .#{$prefix}--image__img {
          position: relative;
          z-index: -1;
      }
   }
}
~~~

### CODE REVIEW

**Comment by annawen1** [comment]
hey @diegomarcuz I see this happening when I tab to the card in the `CTA` story. I select `style` card and `type` video

Screen Shot 2020-06-26 at 3 40 31 PM

**Comment by diegomarcuz** [comment]
Hey @annawen1, could you please clarify? I didn’t understand well, sorry.

**Comment by annawen1** [comment]
> Hey @annawen1, could you please clarify? I didn’t understand well, sorry.



> Hey @annawen1, could you please clarify? I didn’t understand well, sorry.

@diegomarcuz here's a video. When you tab to the card to get the active state that is what happens

Jun-26-2020 16-39-47

**Comment by diegomarcuz** [comment]
> When you press `tab` to the card to get the active state that is what happens

ahhh okk, i will check what is going on, thanks @annawen1

**Comment by diegomarcuz** [comment]
I have updated the code as @annawen1 's feedback.

**Pull request merged**
