### PR TITLE
fix(styles): locale modal accessibility styles

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#3445, #3817, #3819 

### Description

Various accessibility and visual spec fixes to `LocaleModal` (React and web component)

### Changelog

**Changed**

- accessibility and visual spec fixes to `LocaleModal` for both React and web component variations

### CODE REVIEW

**Review by larahanlon2 — COMMENTED** [review]
Visually this looks great. One thing, in the `React` version when I click a region card the search input is automatically in focus when I land on the language list view. This doesn't happen in `Web components`. 

`React`:
Screen Shot 2020-09-23 at 4 44 05 PM

`Web components`:
Screen Shot 2020-09-23 at 4 43 57 PM

**Review by asudoh — COMMENTED** [review]
Good move, one comment; If we can refer to those DOM elements via React ref, instead of via `querySelector()` it's great - Thanks @kennylam!

**Comment by larahanlon2** [comment]
Latest fix to focus looks good to me!

**Review by larahanlon2 — APPROVED** [review]
Looks good to me!

**Comment by jeffchew** [comment]
@kennylam it looks like snapshot files need to be updated for web components.

**Pull request merged**
